/*
 * get_CoriolisMatrix.h
 *
 *  Created on: 15 apr 2019
 *      Author: oliva
 */

#include <eigen3/Eigen/Core>

#ifndef SOURCE_DIRECTORY__VISION_TORQUE_EXAMPLES_FCI_GENERATE_CARTESIAN_POSE_MOTION_INCLUDE_GET_CORIOLISMATRIX_H_
#define SOURCE_DIRECTORY__VISION_TORQUE_EXAMPLES_FCI_GENERATE_CARTESIAN_POSE_MOTION_INCLUDE_GET_CORIOLISMATRIX_H_


Eigen::MatrixXd get_CoriolisMatrix(Eigen::VectorXd q, Eigen::VectorXd dq);


#endif /* SOURCE_DIRECTORY__VISION_TORQUE_EXAMPLES_FCI_GENERATE_CARTESIAN_POSE_MOTION_INCLUDE_GET_CORIOLISMATRIX_H_ */
