/*
 * get_GravityVector.h
 *
 *  Created on: 15 apr 2019
 *      Author: oliva
 */

#include <eigen3/Eigen/Core>

#ifndef SOURCE_DIRECTORY__VISION_TORQUE_EXAMPLES_FCI_GENERATE_CARTESIAN_POSE_MOTION_INCLUDE_GET_GRAVITYVECTOR_H_
#define SOURCE_DIRECTORY__VISION_TORQUE_EXAMPLES_FCI_GENERATE_CARTESIAN_POSE_MOTION_INCLUDE_GET_GRAVITYVECTOR_H_


Eigen::VectorXd get_gravityvector( Eigen::VectorXd q);


#endif /* SOURCE_DIRECTORY__VISION_TORQUE_EXAMPLES_FCI_GENERATE_CARTESIAN_POSE_MOTION_INCLUDE_GET_GRAVITYVECTOR_H_ */
