/*
 * get_FrictionTorque.h
 *
 *  Created on: 16 apr 2019
 *      Author: oliva
 */
#include <eigen3/Eigen/Core>

#ifndef SOURCE_DIRECTORY__VISION_TORQUE_EXAMPLES_FCI_GENERATE_CARTESIAN_POSE_MOTION_INCLUDE_GET_FRICTIONTORQUE_H_
#define SOURCE_DIRECTORY__VISION_TORQUE_EXAMPLES_FCI_GENERATE_CARTESIAN_POSE_MOTION_INCLUDE_GET_FRICTIONTORQUE_H_


Eigen::VectorXd get_friction(Eigen::VectorXd dq);


#endif /* SOURCE_DIRECTORY__VISION_TORQUE_EXAMPLES_FCI_GENERATE_CARTESIAN_POSE_MOTION_INCLUDE_GET_FRICTIONTORQUE_H_ */
